title: "Mi Sitio"
markdown: kramdown
source: ./docs
destination: ./docs/_site
baseurl: ""
permalink: pretty
theme: jekyll-theme-leap-day
description: "Documentaci√≥n usando Jekyll en GitHub Pages"
plugins:
  - jekyll-feed